### ISSUE TITLE
net-im/telegram: User patches applied from a nonstandard directory

### ISSUE THREAD

**Issue by Anonymous1157** [rindeal/gentoo-overlay#10]
The vast majority of Gentoo packages apply user patches with respect to the root of the work directory. `eapply_user` should ideally be run first in `src_prepare`, in case anyone needs to test a patch made against the unmodified sources, or the ebuild should `cd ${WORKDIR}` before running it last as it does now.

I wanted to use a patch and was surprised when it didn't apply on the first try.

**Comment by rindeal** [comment]
it cannot run first as it could break default set of patches and `sed`s, also the default dir is `${S}` rather than `${WORKDIR}`. Anyway, thanks for noticing.
