### ISSUE TITLE
qbittorrent 3.3.6 src_prepare error

### ISSUE THREAD

**Issue by stakewinner00** [rindeal/gentoo-overlay#101]
qbittorrent gives me:
> * ERROR: net-p2p/qbittorrent-3.3.6::rindeal failed (prepare phase):
>  *   The source directory '/var/tmp/portage/net-p2p/qbittorrent-3.3.6/work/qbittorrent-3.3.6-github' doesn't exist

My workarround was to add the next line to the ebuild **GH_DISTFILE="qbittorrent-3.3.6"**

**Comment by rindeal** [comment]
Thank you for reporting the issue and your assistance in this matter. Please don't hesitate to report back if the issue persists.
