### ISSUE TITLE
kde-misc/kdirstat:5 file collision... Oh dear!!

### ISSUE THREAD

**Issue by bobwya** [rindeal/gentoo-overlay#112]
I think you want:
`!kde-misc/kdirstat:*`

As the Qt 5 builds of **kde-misc/kdirstat** are in the main Gentoo tree now.
I got a file collision trying to install the **kde-misc/k4dirstat** package (from your Overlay) - because I already had the package **kde-misc/kdirstat:5::gentoo** installed.

Just a suggestion!
Robert

**Comment by rindeal** [comment]
Yeah, sorry about that. I was reading kdirstat/k4dirstat/qdirstat histories/relations and this mistake somehow got through during the renaming.

Fix is on its way, thank you for the report.
