### ISSUE TITLE
ebuild request: uzbl

### ISSUE THREAD

**Issue by stakewinner00** [rindeal/gentoo-overlay#114]
Gentoo overlay don't have a uzbl ebuild, could you make one or is it out of scope of this overlay?

Thank you.

**Comment by rindeal** [comment]
it's in the scope, however, other overlays already provide ebuilds for it:

```
[1] "booboo" layman/booboo
[2] "petkovich" layman/petkovich
[3] "posativ" layman/posativ
```

You may try the packages from there first and if they wouldn't suffice let me know and I'll see what can I do.

**Comment by stakewinner00** [comment]
These overlays gave me an error in the depend phase, will try to open an issue on the booboo overlay as long as it seems to be the most active and wait them to fix it (or try to fix it for myself but i don't know how ebuilds work).

**Comment by rindeal** [comment]
> or try to fix it for myself but i don't know how ebuilds work

If you're serious about Gentoo you can learn most things here - https://devmanual.gentoo.org/. Ebuilds are just BASH scripts with an extensive function library so it shouldn't be too hard.

**Comment by rindeal** [comment]
so, I've done some preliminary work on it.

Branch: https://github.com/rindeal/gentoo-overlay/tree/uzbl
ETA: max 1 month

**Comment by rindeal** [comment]
So the new package is ready for testing. Instructions on how to do it are [here](https://github.com/rindeal/gentoo-overlay/wiki/FAQ#how-to-test-an-ebuild-in-a-non-default-branch). Once you confirm that it works as it should, I'll merge it to master.

**Comment by stakewinner00** [comment]
Seems that uzbl requires webkit1 to compile. There are another branch called **next** that works with webkit2. From the readme: 

> WebKit2 changes many things compared to WebKit1, some of which impact uzbl greatly. This version of uzbl only supports WebKit1 while older version tried to support both at the same time.

> For a uzbl built on WebKit2 check out the next branch

Is it possible to checkout to **next** branch or is better to generate a (big one) patch?

**Comment by rindeal** [comment]
yeah, I got confused by the numbering `webkitgtk-3.0` is actually webkit1, while `webkit2gtk-3.0` is webkit2. `webkitgtk-1.0` is actually what I'm trying to avoid, because it fails to build and I don't want to know why. So. As `webkitgtk-3.0` compiles fine I'll provide normal releases based on whatever webkit they're currently based on + I may provide live ebuild based on the `next` branch. Sounds fair?

**Comment by stakewinner00** [comment]
Sounds fair. I commented about that branch because I read your comment saying that `it depends on webkit1 which is old and depreciate`, but if we can use webkit1 then I don't see the need for the **next** branch.

**Comment by rindeal** [comment]
well, the quote is true, eg. Fedora banned webkit1 in v27 altogether citing security concerns. But the major reason for me was that it didn't compile. The idea with the `next` branch is actually a good one as my package can now cover also the users for which webkit1 is really a blocker.

So apart from the `next` branch, does it work for you? Have you tested it?

**Comment by stakewinner00** [comment]
I have test the ebuild. It have emerged the webkit2 so uzbl couldn't compile.

**Comment by rindeal** [comment]
Ok, you can pull the update and try again. I've also added the live ebuild so you can try that one as well.

**Comment by stakewinner00** [comment]
It compiles (both versions) but there are some minor issues. If using python2, `dev-python/configparser` should be a dependency, in python3  there is built-in so it's not necessary. 

Thanks for the ebuild :)
