### ISSUE TITLE
Clion 2016.2.2 emerge error

### ISSUE THREAD

**Issue by Randl** [rindeal/gentoo-overlay#117]
When I try to emerge CLion, I get an error 'No such file or directory" [here](https://github.com/rindeal/gentoo-overlay/blob/master/dev-cpp/clion/clion-2016.2.2.ebuild#L31)

**Comment by rindeal** [comment]
Thank you for reporting the issue and your assistance in this matter. Please don't hesitate to report back if the issue persists.
