### ISSUE TITLE
net-im/telegram-desktop-0.10.1-r1: Allow building against ffmpeg-3.2

### ISSUE THREAD

**Issue by Anonymous1157** [rindeal/gentoo-overlay#142]
The current ebuild for this version of Telegram specifies `=media-video/ffmpeg-3.1*:0=[mp3,opus,vorbis,wavpack]` as the version to build against, but the official Gentoo tree no longer includes  ffmpeg 3.1. (I am unable to use the version in the Rindeal tree because I need multilib.) Changing this to `>=media-video/ffmpeg-3.1:0=[mp3,opus,vorbis,wavpack]` (Therefore building against 3.2.2 in my case) compiles and runs just fine.

**Comment by rindeal** [comment]
In my case it caused this https://github.com/rindeal/gentoo-overlay/issues/139. I didn't dig through it much to be honest, but rolling back to 3.1 helped. I may try it again and will see. However please be aware that this package is in the state of graceful death and will be replaced by Cutegram as soon as it gets in shape.

**Comment by Anonymous1157** [comment]
I suspect issue #139 was actually in ffmpeg between 3.2.0 and 3.2.2 for it to have worked for me now.

Thank you for letting me know about Cutegram. I thought the project was dead since there has been no news for a while, but it looked like a great alternative and I look forward to using it when it's ready.
