### ISSUE TITLE
telegram-desktop-9999: patch failed on current release

### ISSUE THREAD

**Issue by skobkin** [rindeal/gentoo-overlay#145]
```
 * Package:    net-im/telegram-desktop-9999
 * Repository: rindeal
 * Maintainer: dev.rindeal+gentoo-overlay@gmail.com
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux pch proxy userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
Initialized empty Git repository in /usr/portage/distfiles/git3-src/telegramdesktop_tdesktop.git/
 * Fetching https://github.com/telegramdesktop/tdesktop.git ...
git fetch https://github.com/telegramdesktop/tdesktop.git +HEAD:refs/git-r3/HEAD --depth 1
remote: Counting objects: 1024, done.
remote: Compressing objects:   0% (1/1007)
// ...
From https://github.com/telegramdesktop/tdesktop
 * [new ref]                    -> refs/git-r3/HEAD
 * [new tag]         v1.0.0     -> v1.0.0
git symbolic-ref refs/git-r3/net-im/telegram-desktop/0/__main__ refs/git-r3/HEAD
 * Checking out https://github.com/telegramdesktop/tdesktop.git to /tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999 ...
git checkout --quiet refs/git-r3/HEAD
GIT NEW branch -->
   repository:               https://github.com/telegramdesktop/tdesktop.git
   at the commit:            7fb1463c43922b34b696741da536dfafce7a6469
 * Applying 0.10.1-revert_Round_radius_increased_for_message_bubbles.patch ...
1 out of 1 hunk FAILED -- saving rejects to file Telegram/Resources/basic.style.rej
[ !! ]
 * ERROR: net-im/telegram-desktop-9999::rindeal failed (prepare phase):
 *   patch -p1  failed with /var/lib/layman/rindeal/net-im/telegram-desktop/files/0.10.1-revert_Round_radius_increased_for_message_bubbles.patch
 * 
 * Call stack:
 *               ebuild.sh, line  115:  Called src_prepare
 *             environment, line 4161:  Called eapply '/var/lib/layman/rindeal/net-im/telegram-desktop/files/0.10.1-revert_Round_radius_increased_for_message_bubbles.patch'
 *             environment, line 1436:  Called _eapply_patch '/var/lib/layman/rindeal/net-im/telegram-desktop/files/0.10.1-revert_Round_radius_increased_for_message_bubbles.patch'
 *             environment, line 1374:  Called __helpers_die 'patch -p1  failed with /var/lib/layman/rindeal/net-im/telegram-desktop/files/0.10.1-revert_Round_radius_increased_for_message_bubbles.patch'
 *   isolated-functions.sh, line  117:  Called die
 * The specific snippet of code:
 *              die "$@"
 * 
 * If you need support, post the output of `emerge --info '=net-im/telegram-desktop-9999::rindeal'`,
 * the complete build log and the output of `emerge -pqv '=net-im/telegram-desktop-9999::rindeal'`.
 * The complete build log is located at '/tmp/portage/net-im/telegram-desktop-9999/temp/build.log.gz'.
 * The ebuild environment file is located at '/tmp/portage/net-im/telegram-desktop-9999/temp/environment'.
 * Working directory: '/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999'
 * S: '/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999'
```

Seems like patch is not working for commits after 1.0 release.

**Comment by rindeal** [comment]
Thanks for the report. This package is no longer developed though and will be replaced with cutegram in the (hopefully) not so distant future. An issue monitoring progress of a community update is here - https://github.com/rindeal/gentoo-overlay/issues/124. I'll remove v9999 from the master branch now as it's no longer fit for purpose.

**Comment by skobkin** [comment]
> will be replaced with cutegram in the (hopefully) not so distant future

Cutegram is cute but AFAIK implements older version of protocol and does not support two-factor authentication for example.

**Comment by rindeal** [comment]
> Cutegram is cute but AFAIK implements older version of protocol and does not support two-factor authentication for example.

That's an inconvenience, but on the other hand it supports secure chats and is much more maintainable - it doesn't require static libraries (tdesktop requires Qt+ffmpeg) and doesn't require non-standard build system (tdesktop requires gyp, cutegram uses cmake).

**Comment by skobkin** [comment]
> it supports secure chats

Yeah, it's a good feature, but not so good if you can not secure your account from SMS highjacking as [happened in Russia](http://appleapple.top/the-opposition-has-disabled-sms-service-hacked-telegram/) for example. So this is two-edged problem. In one hand we have telegram-desktop which can secure our messaging on client-server-client level (we need to trust Telegram servers). In other hand we have Cutegram which does not support 2-factor auth so we need to trust our mobile operator. Both of solutions are not enough secure.

So I think it's a bad idea to completely drop `telegram-desktop` support.

**Comment by rindeal** [comment]
true, but even if I drop telegram-desktop and some users will not be willing to use cutegram, there are still alternatives available, like pre-compiled tdesktop and on-line webogram, which both support 2FA. + IMO adding support for 2FA to cutegram will be much easier than adding secure chats to tdekstop and making it maintainable.
