### ISSUE TITLE
dev-java/idea-2017.1 Filesize does not match recorded size

### ISSUE THREAD

**Issue by romildo** [rindeal/gentoo-overlay#161]
Installation of dev-java/idea-2017.1 fails with the error:

```
!!! Fetched file: ideaIU-2017.1.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      615882928
!!! Expected: 615947647
Refetching... File renamed to '/alt/portage/distfiles/ideaIU-2017.1.tar.gz._checksum_failure_.fpM4QZ'
```

**Comment by rindeal** [comment]
Thanks. Upstream changed the tarball without renaming it, that's why the failure. I fixed it for the community version a few days ago and forgot about checking this version as well. Should be fixed now.
