### ISSUE TITLE
Two desktop entries for dbeaver

### ISSUE THREAD

**Issue by fancywriter** [rindeal/gentoo-overlay#174]
I have noticed it for a long time ago, always forgetting to report or investigate on my own...
I have only one dbeaver-bin installed (4.1.0), slot 3 is uninstalled.

It creates two desktop entries:
```
qlist dbeaver | grep .desktop
/opt/dbeaver4/dbeaver.desktop
/usr/share/applications/_usr_bin_dbeaver4_%U-dbeaver-bin-4.desktop
```
First one seems to be incorrect:
```
cat /opt/dbeaver4/dbeaver.desktop
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Name=DBeaver CE
GenericName=SQL Database Client
Comment=Universal Database Manager and SQL Client.
Path=/usr/share/dbeaver/
Exec=/usr/share/dbeaver/dbeaver
Icon=/usr/share/dbeaver/dbeaver.png
Categories=IDE;Development
WM_CLASS=DBeaver
StartupWMClass=SWT
StartupNotify=true
```
Is it the default one from dbeaver bundle? There is no directory `/usr/share/dbeaver/` for sure.

Second one is correct, though I don't like the name.
```
cat /usr/share/applications/_usr_bin_dbeaver4_%U-dbeaver-bin-4.desktop
[Desktop Entry]
Name=DBeaver 4
Type=Application
Comment=Free universal database manager and SQL client
Exec=/usr/bin/dbeaver4 %U
TryExec=/usr/bin/dbeaver4
Icon=dbeaver4
Categories=Development;Database;IDE;
MimeType=application/x-sqlite3;
StartupWMClass=DBeaver
StartupNotify=true
GenericName=SQL Database Client
```

**Comment by fancywriter** [comment]
Yes, indeed, `dbeaver.desktop` is the default one from `dbeaver-ce-4.1.0-linux.gtk.x86_64.tar.gz`. The best thing to do is just not to copy it to install directory or delete. Not sure if I have to report about it to `dbeaver` project, this desktop file looks very strange, because there is no `/usr/share/dbeaver` directory there too, and `dbeaver` binary with `dbeaver.png` image is stored in the root...

**Comment by rindeal** [comment]
The file from upstream is just a couple of bytes in size, so there is no real reason to delete it. Also the file from upstream is not technically incorrect, it's just that they've made certain choices that are in hand with the upstream requirements. Downstream users are free to customize it to their own environment, which is exactly what I've done in the ebuild, although instead of modifying it I'm just recreating it from the ground up.

**Comment by fancywriter** [comment]
Why it is annoying me, because when I try to type `dbeaver` in krunner, it suggests me wrong version at the top, and correct version at the second place. :)
I will just delete it manually for now, but will think how to remove it from ebuild in future - it's not about saving bytes.

**Comment by rindeal** [comment]
Well, you didn't mention that, also I doubt the file is at fault as the directory `/opt/*` is not scanned by krunner. It's more likely that you have some residues of previous installations in `/usr/share/applications` or `~/.local/share/applications`. Try running `grep -r -i -l dbeaver {~/.local,/usr}/share/applications` and see if it finds something that wasn't installed by the ebuild.

**Comment by fancywriter** [comment]
Oh, you're right. Really, it didn't help. Found wrong `~/.local/share/applications/DBeaver.desktop`, deleted it. Also found few other stale files... deleted them too.
