### ISSUE TITLE
Code correctness proof

### ISSUE THREAD

**Issue by 0xd34df00d** [rindeal/gentoo-overlay#183]
Hi,

I am very much interested in formal verification methods, so this claim in your README caught my eye: `code in ebuilds is correct`. How do you prove that?

Thanks.

**Comment by rindeal** [comment]
Hi @0xd34df00d,

thank you for your interest. The word _correct_ as used in this sentence doesn't imply formal correctness (the term used in theoretical computer science), rather it means simply _free from error_ as defined in the Oxford dictionary (generally speaking, but mostly the ebuilds run flawlessly indeed).
