### ISSUE TITLE
net-im/telegram: update to 0.9.56

### ISSUE THREAD

**Issue by rindeal** [rindeal/gentoo-overlay#45]
- `DEFINES += TDESKTOP_DISABLE_DESKTOP_FILE_GENERATION`
- c++14
- https://github.com/rindeal/gentoo-overlay/pull/44
- bump qt-telegram-static to 2016-06-25
- xdg.eclass
- drop Qt < 5.6.0 warning

**Comment by jorgicio** [comment]
July 25? :S

**Comment by rindeal** [comment]
fixed, thanks
