### ISSUE TITLE
dev-qt/qt-telegram-static-5.6.0_p20160804 fetch failed

### ISSUE THREAD

**Issue by soredake** [rindeal/gentoo-overlay#68]
https://gist.github.com/soredake/e67cbc670df73b48807c5049635e3e23

**Comment by rindeal** [comment]
Thank you for reporting the issue. The date-based revisions obviously do not work well, I'll switch to classic tag-based.

**Comment by soredake** [comment]
> emerge --digest -1 -a dev-qt/qt-telegram-static
Still fails.
