### ISSUE TITLE
>=net-im/telegram-desktop-0.10: Build own copy of >=media-video/ffmpeg-3.0

### ISSUE THREAD

**Issue by Anonymous1157** [rindeal/gentoo-overlay#70]
I have been using `net-im/telegram-desktop` for a while, but I'm having trouble modifying my system to accept the upgrade from 0.9.56 to 0.10.1-r1 because it requires a version of `media-video/ffmpeg` that is currently masked. Would it be possible for this ebuild to build its own ffmpeg? It could use the existing qt-static infrastructure to use a separately compiled static build, or work similar to other ebuilds that need to do this and build a copy as part of the same build, controlled by a "system-ffmpeg" useflag.

**Comment by rindeal** [comment]
well, this has already been brought up [in this thread](https://github.com/rindeal/gentoo-overlay/commit/0fab8e1dde946585782810f81b7fe1f4b76a872f#commitcomment-18577729). But I will sum it up once more.

>=ffmpeg-3 is masked in the main tree for no good reason. Putting `<media-video/ffmpeg-3.2` to `package.unmask` is not going to blow up your machine. If some package eventually fails to compile then the usual fix is to update it to a newer version. You could also nag gentoo-devs to stabilize those packages if "unmasking" and "unstable" packages bother you too much.

The qt-telegram-static package is an ugly hack and adding more packages like that would be really nasty. The only reason for introducing new *-static package would be another heavily patched library.
