### ISSUE TITLE
net-im/telegram-desktop: Patch adaptive layout to apply at smaller screen resolutions

### ISSUE THREAD

**Issue by Anonymous1157** [rindeal/gentoo-overlay#71]
Telegram supports an alternative chat layout where a user's own messages are shown on the left, in line with those of other users. After its introduction in version 0.9.26, it was immediately modified in the next version to only apply if Telegram's window is larger than 1366 pixels wide, whereas the original implementation worked at lower resolutions. My monitors are 1280x1024 but I wanted to continue to use the new layout. Applying this one-liner patch is the primary reason I have been using the Telegram ebuild from this repo. (Thank you for it, by the way!)

I haven't tested it with `net-im/telegram-desktop-0.10.1-r1` but it was working with all older versions up to `0.9.56` and would be trivial to recreate if it no longer applies cleanly.

```
diff --recursive -U3 a/Telegram/Resources/style.txt b/Telegram/Resources/basic.style
--- a/Telegram/Resources/basic.style    2016-02-22 02:07:44.000000000 -0500
+++ b/Telegram/Resources/basic.style    2016-02-25 23:47:29.300019831 -0500
@@ -53,7 +53,7 @@
 wndMinWidth: 380px;

 adaptiveNormalWidth: 640px;
-adaptiveWideWidth: 1366px;
+adaptiveWideWidth: 1024px;

 wndMinHeight: 480px;
 wndDefWidth: 800px;
```

**Comment by rindeal** [comment]
I have also one monitor 1280px wide so I'll give this patch a try and eventually include it. Thank you.

**Comment by rindeal** [comment]
Development of tdesktop pkg is currently frozen.
