### ISSUE TITLE
net-im/telegram requires dev-libs/libpcre[pcre16]

### ISSUE THREAD

**Issue by Anonymous1157** [rindeal/gentoo-overlay#9]
The static Qt build for Telegram requires the system libpcre to be built with pcre16 support. If the USE flag is not enabled, the build fails while configuring Qt with the following error:
```
Creating qmake...
........................................................................................Done.
Running configuration tests...
PCRE support cannot be enabled due to functionality tests!
```
When it is enabled, Telegram builds and runs just fine.

**Comment by rindeal** [comment]
Thanks

**Comment by rindeal** [comment]
Hi @Anonymous1157, I've had a second look at the Qt dependencies and did some copy-pasting from the official Qt packages, then some more and as a result I decided to split the telegram package to two - Qt and Telegram itself. Another improvement of this move is that Qt won't have to be rebuilt everytime.

Can you please test it out?

```sh
root# emerge -1v \=net-im/telegram-0.9.24-r2::rindeal
```

**Comment by Anonymous1157** [comment]
@rindeal Thanks! I've been using the older ebuild to test 0.9.26 and I wanted to apply a user patch. Needless to say, that was painful. This will help.

The new Qt ebuild failed to properly download Telegram's patch. I copied the patch from 0.9.24 into my distfiles and that one worked. The file isn't trememdously huge and doesn't appear to have changed between 0.9.24 and 26; maybe it could be included in the overlay?
```
>>> Downloading 'https://github.com/telegramdesktop/tdesktop/raw/master@{2016-02-07}/Telegram/_qtbase_5_5_1_patch.diff'
--2016-02-27 10:56:16--  https://github.com/telegramdesktop/tdesktop/raw/master@%7B2016-02-07%7D/Telegram/_qtbase_5_5_1_patch.diff
Resolving github.com... 192.30.252.131
Connecting to github.com|192.30.252.131|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/telegramdesktop/tdesktop/a6861c3e945712b3b09fba75c0bf25a12e79c97f/Telegram/_qtbase_5_5_1_patch.diff [following]
--2016-02-27 10:56:17--  https://raw.githubusercontent.com/telegramdesktop/tdesktop/a6861c3e945712b3b09fba75c0bf25a12e79c97f/Telegram/_qtbase_5_5_1_patch.diff
Resolving raw.githubusercontent.com... 199.27.76.133
Connecting to raw.githubusercontent.com|199.27.76.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 590960 (577K) [text/plain]
Saving to: ‘/usr/portage/distfiles/telegram-qtstatic-5.5.1_p20160207-qtbase.patch’

/usr/portage/distfi 100%[=====================>] 577.11K   757KB/s   in 0.8s   

2016-02-27 10:56:18 (757 KB/s) - ‘/usr/portage/distfiles/telegram-qtstatic-5.5.1_p20160207-qtbase.patch’ saved [590960/590960]

!!! Fetched file: telegram-qtstatic-5.5.1_p20160207-qtbase.patch VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      590960
!!! Expected: 591192
```

**Comment by rindeal** [comment]
Oh, I didn't notice the patch changed when I switched to date based revisions in 00c56b1891a8c7342ad19e4fb7f327f9eecc8d52. Anyway, now it's fixed.

The patch is not that big, but still it has >500kB and Gentoo discourages files over 50kB to be placed in repos.
